'''
This is the crew Orchastration Module.
This module is responsible for assembling the Crew(Agent, Tasks, Tool)
It serves as an entry point for the agentic Workflow.

Key Responsibility:

- Instantiate the agents and Task
- Configure CrewAI execution process
- Kick Off
'''

from crewai import Crew, Process
from src.agents.agents import create_agents
from src.agents.tasks import create_tasks

def run_financial_crew(ticker: str) -> str:
    '''
    Initializes and executes the financial analysis crew for a specific stock
    Args: stock ticker
    returns: final markdown report generated by the strategist Agent
    '''
    quant_agent, strategist_agent = create_agents()

    # Assign the work(create task)
    tasks = create_tasks(quant_agent=quant_agent, strategist_agent=strategist_agent, ticker=ticker)

    # Assemble the crew
    financial_crew = Crew(agents=[quant_agent, strategist_agent],
                          tasks= tasks, 
                          process= Process.sequential,
                          verbose=True # Logs every step to console
                          )


    # Start the Crew AI Analysis
    print(f"\n Kicking off Financial Analysis for {ticker}...")                
    result = financial_crew.kickoff()
    
    return result